### ISSUE TITLE
Consume Email VC 不能按预期 work

### ISSUE THREAD

**Issue by linchen1987** [blocklet/wallet-playground#29]
- [x] 无法拿到 user email 数据 @linchen1987 
- [ ] 扫码后显示“没有匹配的VC” @NateRobinson

**Comment by linchen1987** [comment]
![image](https://user-images.githubusercontent.com/11010275/109450313-91c86300-7a85-11eb-917f-664c6333bf31.png)

访问 https://playground.abtwallet.io/full 使用移动端钱包测试上图中这3个功能时，提示“没有匹配的VC”。

不知道是否和预期行为一致，如果不一致，可能需要修复。

**Comment by NateRobinson** [comment]
> ![image](https://user-images.githubusercontent.com/11010275/109450313-91c86300-7a85-11eb-917f-664c6333bf31.png)
> 
> 访问 https://playground.abtwallet.io/full 使用移动端钱包测试上图中这3个功能时，提示“没有匹配的VC”。
> 
> 不知道是否和预期行为一致，如果不一致，可能需要修复。

已验证线上的功能是正常的
